-- ROLE
CREATE TABLE `role` (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
);

-- USER
CREATE TABLE `user` (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(45) NOT NULL,
  password VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  roleId INT NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  CONSTRAINT FKrole FOREIGN KEY (roleId) REFERENCES `role` (id)
);

-- GAME
CREATE TABLE game (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
);

-- ITEM
CREATE TABLE item (
  id INT NOT NULL AUTO_INCREMENT,
  gameId INT NOT NULL,
  name VARCHAR(45) NOT NULL,
  description VARCHAR(45),
  image BLOB,
  PRIMARY KEY (id),
  CONSTRAINT FKGame FOREIGN KEY (gameId) REFERENCES game (id)
);

-- INVENTORY
CREATE TABLE inventory (
  id INT NOT NULL AUTO_INCREMENT,
  itemId INT NOT NULL,
  userId INT NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FKItem FOREIGN KEY (itemId) REFERENCES item (id),
  CONSTRAINT FKUser FOREIGN KEY (userId) REFERENCES `user` (id)
);